name: 'AppImage bash'
description: 'Used to generate AppImage packages'
inputs:
  version_url:
    description: 'URL of tar.gz to download'
    required: true
  version_file:
    description: 'File where is stored version string'
    required: true
  version_icon:
    description: 'Name of the app icon'
    required: true
  version_directory:
    description: 'If specific directory is required'
    required: false
  version_bash:
    description: 'Adding regular expression if needed to get version string from version file'
    required: false
  version_check:
    description: 'If the version of the app needs to be checked'
    required: true
    default: verify
  version_only:
    description: 'If we need only version and then stop execution'
    required: true
    default: update
outputs:
  app_update_needed:
    value: "0"
    description: 'Decision if the AppImage needs to be updated'
runs:
  using: "composite"
  steps:
    - run: echo "::set-env name=INPUT_VERSION_URL::${{ inputs.version_url }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_FILE::${{ inputs.version_file }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_BASH::${{ inputs.version_bash }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_ICON::${{ inputs.version_icon }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_DIRECTORY::${{ inputs.version_directory }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_CHECK::${{ inputs.version_check }}"
      shell: bash
    - run: echo "::set-env name=INPUT_VERSION_ONLY::${{ inputs.version_only }}"
      shell: bash
    - run: chmod +x ${{ github.action_path }}/build.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/build.sh
      shell: bash
